[package]
name = "rcli"
version = "0.1.0"
authors = ["Joshua Hu <dtjhu123@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
csv = "1.3.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
